<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>GrpcBank.Gateway</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.ClientFactory" Version="$(GrpcVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GrpcBank.Contracts\GrpcBank.Contracts.csproj" />
  </ItemGroup>

</Project>
