<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>GrpcBank.LedgerService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="$(GrpcVersion)" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="$(GrpcVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GrpcBank.Contracts\GrpcBank.Contracts.csproj" />
  </ItemGroup>

</Project>
